"""
convert_model.py — Post-training Converter
===========================================
Chạy script này SAU KHI trainAI.py đã hoàn thành thành công.
Nó sẽ đọc 3 file output của training và sinh ra các file C++ cần thiết cho firmware.

Input  (từ model_output/):
  - model.tflite        → mảng byte hex cho ESP32
  - scaler_params.json  → mean, std (vật lý cảm biến thật)
  - quant_params.json   → input/output quantization scale & zero_point

Output (vào src/):
  - model_data.h        → khai báo extern mảng model
  - model_data.cpp      → định nghĩa mảng byte TFLite
  - norm_params.h       → mean[], inv_std[], quant params — hardcode vào firmware

Cách chạy:
    python convert_model.py
"""

import json
import struct
from pathlib import Path

# ─────────────────────────────────────────────────────────────
# CẤU HÌNH
# ─────────────────────────────────────────────────────────────
MODEL_OUTPUT_DIR = Path("model_output")
SRC_DIR          = Path("src")
SRC_DIR.mkdir(exist_ok=True)

TFLITE_PATH      = MODEL_OUTPUT_DIR / "model.tflite"
SCALER_PATH      = MODEL_OUTPUT_DIR / "scaler_params.json"
QUANT_PATH       = MODEL_OUTPUT_DIR / "quant_params.json"

BYTES_PER_ROW    = 12    # số byte hex mỗi dòng trong model_data.cpp

# ─────────────────────────────────────────────────────────────
# BƯỚC 1: Kiểm tra file đầu vào
# ─────────────────────────────────────────────────────────────
def check_inputs():
    missing = []
    for p in [TFLITE_PATH, SCALER_PATH, QUANT_PATH]:
        if not p.exists():
            missing.append(str(p))
    if missing:
        print("❌ Không tìm thấy các file sau — hãy chạy trainAI.py trước:")
        for m in missing:
            print(f"   {m}")
        return False
    return True

# ─────────────────────────────────────────────────────────────
# BƯỚC 2: model.tflite → model_data.h + model_data.cpp
# ─────────────────────────────────────────────────────────────
def convert_model():
    data = TFLITE_PATH.read_bytes()
    size = len(data)
    size_kb = size / 1024

    print(f"\n[1/3] model.tflite → model_data.h / model_data.cpp")
    print(f"      Kích thước: {size_kb:.1f} KB ({size:,} bytes)")

    if size_kb > 60:
        print(f"      ⚠️  Model > 60KB — kiểm tra lại cấu trúc nếu Flash bị hạn chế")

    # ── model_data.h ────────────────────────────────────────
    header_content = """\
#pragma once
// AUTO-GENERATED by convert_model.py — DO NOT EDIT
// Source: model_output/model.tflite

#include <cstdint>

extern const unsigned char  gesture_model_tflite[];
extern const unsigned int   gesture_model_tflite_len;
"""
    (SRC_DIR / "model_data.h").write_text(header_content, encoding="utf-8")
    print(f"      ✅ Đã tạo: src/model_data.h")

    # ── model_data.cpp ──────────────────────────────────────
    hex_rows = []
    for i in range(0, size, BYTES_PER_ROW):
        chunk = data[i : i + BYTES_PER_ROW]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        hex_rows.append(f"  {hex_str},")

    cpp_content = f"""\
// AUTO-GENERATED by convert_model.py — DO NOT EDIT
// Source: model_output/model.tflite
// Size  : {size_kb:.1f} KB ({size:,} bytes)

#include "model_data.h"

alignas(8) const unsigned char gesture_model_tflite[] = {{
{chr(10).join(hex_rows)}
}};

const unsigned int gesture_model_tflite_len = {size}U;
"""
    (SRC_DIR / "model_data.cpp").write_text(cpp_content, encoding="utf-8")
    print(f"      ✅ Đã tạo: src/model_data.cpp")

# ─────────────────────────────────────────────────────────────
# BƯỚC 3: scaler_params.json + quant_params.json → norm_params.h
# ─────────────────────────────────────────────────────────────
def convert_norm_params():
    print(f"\n[2/3] scaler_params.json + quant_params.json → norm_params.h")

    with open(SCALER_PATH) as f:
        scaler = json.load(f)
    with open(QUANT_PATH) as f:
        quant  = json.load(f)

    mean_vals = scaler["mean"]   # list[6] — vật lý thật từ X_train_raw
    std_vals  = scaler["std"]    # list[6]
    axes      = scaler["axes"]   # ["ax","ay","az","gx","gy","gz"]

    # ── Tối ưu: tính inv_std = 1/std trên Python, MCU chỉ cần NHÂN ──
    inv_std_vals = [1.0 / s for s in std_vals]

    classes      = quant["classes"]
    n_classes    = len(classes)
    inp_scale    = quant["input_scale"]
    inp_zp       = quant["input_zp"]
    out_scale    = quant["output_scale"]
    out_zp       = quant["output_zp"]
    window_size  = quant["window_size"]
    n_axes       = quant["n_axes"]

    # ── Định dạng array literal ──────────────────────────────
    def fmt_float_arr(vals, label):
        lines = []
        for i, (v, ax) in enumerate(zip(vals, axes)):
            lines.append(f"  {v:.8f}f,  // [{i}] {ax} — {label}")
        return "\n".join(lines)

    mean_block    = fmt_float_arr(mean_vals,    "mean")
    inv_std_block = fmt_float_arr(inv_std_vals, "1/std (pre-computed)")

    class_names_block = "\n".join(
        f'  "{c}",  // [{i}]' for i, c in enumerate(classes)
    )

    header = f"""\
#pragma once
// AUTO-GENERATED by convert_model.py — DO NOT EDIT
// Sources: model_output/scaler_params.json
//          model_output/quant_params.json
//
// Tối ưu MCU: inv_std = 1/std được tính sẵn trên Python.
// Trên ESP32-S3, phép NHÂN float nhanh hơn phép CHIA 2-3 lần.
// Z-score trên firmware: z = (x - mean) * inv_std  (không dùng /)

#include <cstdint>

// ─── Cấu hình mô hình ────────────────────────────────────────
static constexpr int  HAR_WINDOW_SIZE = {window_size};   // samples (3.0s @ 50Hz)
static constexpr int  HAR_NUM_AXES    = {n_axes};        // ax,ay,az,gx,gy,gz
static constexpr int  HAR_NUM_CLASSES = {n_classes};     // số class output

// ─── Z-Score params (fit trên X_train_raw — vật lý thật) ─────
//     KHÔNG được thay đổi thứ tự: [ax, ay, az, gx, gy, gz]
static constexpr float HAR_MEAN[{n_axes}] = {{
{mean_block}
}};

// inv_std = 1.0f / std  →  dùng phép nhân thay vì chia trên MCU
static constexpr float HAR_INV_STD[{n_axes}] = {{
{inv_std_block}
}};

// ─── TFLite Int8 Quantization params ─────────────────────────
//     Dùng để: float_z → int8 (input), int8 → float prob (output)
static constexpr float   HAR_INPUT_SCALE      = {inp_scale:.8f}f;
static constexpr int32_t HAR_INPUT_ZERO_POINT = {inp_zp};
static constexpr float   HAR_OUTPUT_SCALE     = {out_scale:.8f}f;
static constexpr int32_t HAR_OUTPUT_ZERO_POINT= {out_zp};

// ─── Tên class theo index ─────────────────────────────────────
static const char* HAR_CLASS_NAMES[{n_classes}] = {{
{class_names_block}
}};
"""
    (SRC_DIR / "norm_params.h").write_text(header, encoding="utf-8")
    print(f"      ✅ Đã tạo: src/norm_params.h")

    # In tóm tắt để kiểm tra
    print(f"\n      📋 Tóm tắt thông số:")
    for i, ax in enumerate(axes):
        print(f"         {ax}: mean={mean_vals[i]:+.4f}  std={std_vals[i]:.4f}  inv_std={inv_std_vals[i]:.4f}")
    print(f"\n      Input  quant: scale={inp_scale:.6f}, zp={inp_zp}")
    print(f"      Output quant: scale={out_scale:.6f}, zp={out_zp}")
    print(f"      Classes ({n_classes}): {', '.join(classes)}")

# ─────────────────────────────────────────────────────────────
# BƯỚC 4: Gợi ý bước tiếp theo
# ─────────────────────────────────────────────────────────────
def print_next_steps():
    print(f"""
[3/3] Hướng dẫn tích hợp vào PlatformIO
      ──────────────────────────────────
      1. Copy các file sau vào thư mục src/ của firmware:
           src/model_data.h
           src/model_data.cpp
           src/norm_params.h

      2. Thêm thư viện TFLite Micro vào platformio.ini:
           lib_deps =
               https://github.com/tensorflow/tflite-micro-arduino-examples

      3. Build và flash như bình thường.

      4. Kiểm tra Serial Monitor:
           - Xem thử inference time (ms)
           - Xem confidence score của mỗi class
""")

# ─────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────
def main():
    print("=" * 55)
    print("  convert_model.py  —  TFLite → C++ Converter")
    print("=" * 55)

    if not check_inputs():
        return

    convert_model()
    convert_norm_params()
    print_next_steps()

    print("=" * 55)
    print("  ✅ DONE! Sẵn sàng tích hợp vào firmware.")
    print("=" * 55)

if __name__ == "__main__":
    main()