#pragma once
// AUTO-GENERATED by convert_model.py — DO NOT EDIT
// Source: model_output/model.tflite

#include <cstdint>

extern const unsigned char  gesture_model_tflite[];
extern const unsigned int   gesture_model_tflite_len;
