#pragma once
// AUTO-GENERATED by convert_model.py — DO NOT EDIT
// Sources: model_output/scaler_params.json
//          model_output/quant_params.json
//
// Tối ưu MCU: inv_std = 1/std được tính sẵn trên Python.
// Trên ESP32-S3, phép NHÂN float nhanh hơn phép CHIA 2-3 lần.
// Z-score trên firmware: z = (x - mean) * inv_std  (không dùng /)

#include <cstdint>

// ─── Cấu hình mô hình ────────────────────────────────────────
static constexpr int  HAR_WINDOW_SIZE = 150;   // samples (3.0s @ 50Hz)
static constexpr int  HAR_NUM_AXES    = 6;        // ax,ay,az,gx,gy,gz
static constexpr int  HAR_NUM_CLASSES = 5;     // số class output

// ─── Z-Score params (fit trên X_train_raw — vật lý thật) ─────
//     KHÔNG được thay đổi thứ tự: [ax, ay, az, gx, gy, gz]
static constexpr float HAR_MEAN[6] = {
  0.15883821f,  // [0] ax — mean
  0.01432643f,  // [1] ay — mean
  -0.02781012f,  // [2] az — mean
  -0.44101688f,  // [3] gx — mean
  0.47294450f,  // [4] gy — mean
  -0.21489604f,  // [5] gz — mean
};

// inv_std = 1.0f / std  →  dùng phép nhân thay vì chia trên MCU
static constexpr float HAR_INV_STD[6] = {
  1.48762882f,  // [0] ax — 1/std (pre-computed)
  1.90575035f,  // [1] ay — 1/std (pre-computed)
  1.96947049f,  // [2] az — 1/std (pre-computed)
  0.04014855f,  // [3] gx — 1/std (pre-computed)
  0.02478677f,  // [4] gy — 1/std (pre-computed)
  0.02976099f,  // [5] gz — 1/std (pre-computed)
};

// ─── TFLite Int8 Quantization params ─────────────────────────
//     Dùng để: float_z → int8 (input), int8 → float prob (output)
static constexpr float   HAR_INPUT_SCALE      = 0.09810095f;
static constexpr int32_t HAR_INPUT_ZERO_POINT = -9;
static constexpr float   HAR_OUTPUT_SCALE     = 0.00390625f;
static constexpr int32_t HAR_OUTPUT_ZERO_POINT= -128;

// ─── Tên class theo index ─────────────────────────────────────
static const char* HAR_CLASS_NAMES[5] = {
  "bicep_curl",  // [0]
  "idle",  // [1]
  "lateral_raise",  // [2]
  "shoulder_press",  // [3]
  "tricep_ext",  // [4]
};
